run with bundle

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -46,7 +46,8 @@ jobs:
       - name: Build and Publish Testflight
         run: |
           cd ios
-          fastlane beta version:${{ needs.version.outputs.version }} build_number:${{ needs.version.outputs.build_number }} > /dev/null 2>&1 || (echo "Fastlane failed" && exit 1)
+          bundle install
+          bundle exec fastlane beta version:${{ needs.version.outputs.version }} build_number:${{ needs.version.outputs.build_number }} > /dev/null 2>&1 || (echo "Fastlane failed" && exit 1)
         env:
           APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
           APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
@@ -94,7 +95,8 @@ jobs:
       - name: Build and Publish Testflight
         run: |
           cd macos
-          fastlane beta version:${{ needs.version.outputs.version }} build_number:${{ needs.version.outputs.build_number }} > /dev/null 2>&1 || (echo "Fastlane failed" && exit 1)
+          bundle install
+          bundle exec fastlane beta version:${{ needs.version.outputs.version }} build_number:${{ needs.version.outputs.build_number }} > /dev/null 2>&1 || (echo "Fastlane failed" && exit 1)
         env:
           APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
           APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
@@ -160,7 +162,8 @@ jobs:
       - name: Publish Google Play
         run: |
           cd android
-          fastlane beta
+          bundle install
+          bundle exec fastlane beta
 
       - name: Upload Debug Symbols to Sentry
         env:
